import React from "react";
import Carousel from "../../components/swiper/Carousel";

const CallForPaper = () => {
  return (
    <div className=" md:px-16 px-5 md:my-4 my-2 md:min-h-screen">
      <div>
        <h1 className="text-center font-bold font-serif text-2xl md:text-4xl">
          Call for Papers
        </h1>
        <div className="h-1 mt-2 rounded-xl bg-gradient-to-r from-white via-black to-white relative" />
        <Carousel />
      </div>
      <div className="md:text-xl text-lg space-y-4 font-semibold mt-3 tracking-wide text-justify md:px-16">
        <p className="animate-pulse ">
          Papers will be submitted through Microsoft CMT Portal
        </p>
        <p className="text-left">Submission Page:</p>
        <a
          className="text-blue-700 underline"
          href="https://cmt3.research.microsoft.com/MPTEAS2024"
        >
          https://cmt3.research.microsoft.com/MPTEAS2024
        </a>
        <p className="text-left">
          Academicians/Researchers across the globe are invited to present their
          original work with Publication Opportunity in Scopus/SCImago/DBLP/UGC
          CARE Indexed Conference Proceedings
        </p>
        <p className="md:font-extrabold text-left">
          “Proceedings of MP-TEAS 2024” will be published in two volumes of
          Springer Nature's Scopus/SCI indexed book series “Lecture Notes in
          Networks and Systems” <br />
        </p>
        <a
          className="text-blue-700 underline font-semibold"
          href="https://www.springer.com/series/15179"
        >
          https://www.springer.com/series/15179
        </a>
        <p className="text-left">
          The LNNS Series of Speinger Nature is indexed in SCOPUS, SCImago
          INSPEC, WTI Frankfurt eG, zbMATH, DBLP, Google Scholar and
          Springerlink, and this is also indexed by UGC Care.
        </p>
      </div>
      <div className="mt-4 w-full p-2">
        <div className=" h-1 rounded-xl bg-gradient-to-r from-white via-black to-white relative" />
        <p className="text-center my-4">
          <span className="font-semibold text-xl">
            Important Dates [ Deadlines ]
          </span>
        </p>
        <div className="flex flex-col gap-2">
          <table className=" text-xs md:text-xl text-center">
            <thead>
              <tr>
                <th>Subject</th>
                <th>Last Date</th>
                <th>Extended Date</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>Manuscript Submission</td>
                <td className="font-semibold p-1">Oct 20, 2024</td>
                <td>-</td>
              </tr>
              <tr>
                <td>Notification of acceptance</td>
                <td className="font-semibold p-1">Oct 25, 2024</td>
                <td>-</td>
              </tr>
              <tr>
                <td>Revised Submission</td>
                <td className="font-semibold p-1">Oct 31, 2024</td>
                <td>-</td>
              </tr>
              <tr>
                <td>Camera Ready Paper Due</td>
                <td className="font-semibold p-1">Oct 05, 2024 </td>
                <td>-</td>
              </tr>
              <tr>
                <td>Last Date of Registration(Early Birds)</td>
                <td className="font-semibold p-1">Nov 10, 2024</td>
                <td>-</td>
              </tr>
              <tr>
                <td>Last date of Registration</td>
                <td className="font-semibold p-1">Nov 12, 2024</td>
                <td>-</td>
              </tr>
              <tr>
                <td className="text-red-500 font-bold">Conference Dates</td>
                <td className="font-semibold p-1">Nov 22-24, 2024</td>
                <td>-</td>
              </tr>
            </tbody>
          </table>
        </div>
        <div className=" text-xl space-y-4 mt-3 tracking-wide text-justify md:px-16 font-normal">
          <li className="text-xl font-extrabold ">Initial Screening </li>
          <p>
            The MP-TEAS 2024 Program team will be checking plagiarism of all the
            submitted papers for ensuring the originality of content using
            Turnitin/iThenticate. Hence, authors are advised in their own
            interest, to use a tool like Turnitin, iThenticate etc. to check the
            plagiarism level of their manuscripts before submission. The
            originality report generated by the tool may also be submitted at
            the time of paper submission. The paper having plagiarism above the
            minimum level will be dropped from next round of review process.
          </p>
          <li className="text-xl font-extrabold">Three Tier Review Process </li>
          <p>
            In the first round of review, the papers submitted by the authors
            will be assessed on the basis of their technical suitability, scope
            of work. The peer review by three experts on the basis of
            originality, novelty, clarity, completeness, relevance, significance
            and research contribution will be taken. Final decision regarding
            acceptance of papers will be based upon review remarks received
            after the comments by at least 3 reviewers. During the third and
            final round of three tier process the technical program committee
            will see all reviews and then decide the decision for the paper. The
            final decision of the papers will be by the Chairs of the Technical
            Program Committee considering the reviews, plagiarism and theme,
            shortlisted papers will be accepted for presentation in the MP-TEAS
            2024 and publication in the proceedings.
          </p>
          <li className="text-xl font-extrabold">Publication</li>
          <div className="flex flex-col gap-3">
            <p>
              Publication Top 60 papers will be published in Scoupus indexed
              Conference Proceedings by Springer Nature. “Proceedings of MP-TEAS
              2024” will be published in two volumes of Springer Nature's
              Scopus/SCI indexed book series “Lecture Notes in Networks and
              Systems” (https://www.springer.com/series/15179) Ranking of papers
              will be done on following basis:
            </p>
            <p className="md:font-semibold text-left">
              1. Paper Acceptance: 10 marks(strong-10, normal-7, weak-5, very
              weak-3 as per the Reviewers' decision)
            </p>
            <p className="md:font-semibold text-left">
              2. Successful Presentation of the paper in Conference: 10
              marks(strong-10, normal-7, weak-5, very weak-3 as per the Session
              Chairs' decision)
            </p>
            <p>
              Therefore, Marks Obtained out of Total 20 marks will give the
              ranking.
            </p>
            <p>
              For example, if paper is weakly accepted (5), but strongly
              presented with satisfying all queries (e.g. 10 out of 10) will get
              5+10=15, and hence can get a higher rank.
            </p>
            <p>
              Strongly accepted will definitely be published as top 80 papers,
              because even if it is presented weak and get 5 marks, then too,
              total marks can be 15. Normally 15 and above will get published in
              top 80.
            </p>
            <p>
              Sample{" "}
              <a className="text-blue-500 hover:underline" href="">
                Click Here!
              </a>{" "}
            </p>
            <p>
              Word Template Download{" "}
              <a
                target="_blank"
                className="text-blue-500 hover:underline"
                href="https://www.springer.com/gp/authors-editors/conference-proceedings/editors/word-template/19338734"
              >
                Click Here!
              </a>
            </p>
            <p>
              LATEX Template Download{" "}
              <a
                target="_blank"
                className="text-blue-500 hover:underline"
                href="https://www.springer.com/in/livingreviews/latex-templates?Frontend@footer-livingreviews.bottom3.url"
              >
                Click Here!
              </a>
            </p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default CallForPaper;
