 export const committeeMembers = [
    "Dr. Ritu Shrivastava, Assistant Professor, Bahrain Polytechnic, Isa Town, Kingdom of Bahrain.",
    "Dr. Vijay Kumar Vyas, Sur University College, Oman.",
    "Dr Satendra Narayan, CSE, Sheridan Institute of Technology Ontario Canada.",
    "Dr M M Awad, Faculty of Engineering, Mansoura University, Egypt.",
    "Dr. Somaditya Sen, Associate Professor in Physics department at Indian Institute of Technology (IIT) Indore.",
    "Prof Dr. Tanmoy Som, Prof. IIT BHU, Department of Mathematical Science, INDIAN INSTITUTE OF TECHNOLOGY BHU, VARANASI.",
    "Dr. S.C. Choube, Professor, Department of Electrical & Electronics, RGPV, Bhopal.",
    "Dr. Jitendra Agarwal, Associate Professor, Department of Computer Science and Engineering UIT, RGPV, Bhopal.",
    "Dr. Audithan Sivaraman, Professor Department of Information Technology Netaji Subash University of Technology, Delhi.",
    "Dr. A.K. Katiyar, Professor Dept. of Civil Engineering, MANIT, Bhopal.",
    "Dr. Aseem Tiwari, Professor, Mechanical Department RGPV, Bhopal.",
    "Er. Manoj Acharya, Rtd. ENC UADP, Bhopal.",
    "Dr. Rajesh Kumar Nema, Professor, Department of Electronics and communication Engineering, IES College of Technology, Bhopal.",
    "Dr. Shweta Singh, Associate Professor, Department of Electronics and Communication Engineering, IES College of Technology, Bhopal.",
    "Dr. Monika Vyas, Professor, Department of Civil Engineering, IES College of Technology, Bhopal.",
    "Dr. Rashmi Shrivastava, Professor, Department of Basic Science, IES College of Technology, Bhopal.",
    "Dr. Preeti Chincholekar, Prof. Dept. of basic Science, IES College of Technology, Bhopal.",
    "Dr. Pramod Patel, Dept. of Electronics and Communication, IES College of Technology, Bhopal.",
    "Dr. Anita Soni, Prof. Dept. of Science and IT, IES University. Bhopal.",
    "Dr. Ashish Mishra, Assistant Prof. Dept. of Computer Science and engineering Jaypee Institute of Information and Technology, Noida.",
    "Dr. Raju Baraskar, Associate Prof. School of IT, UIT, RGPV, Bhopal.",
    "Dr. Bhawani Shankar Mishra, Associate Prof. Dept. of Computer Science & Engineering, KIIT, Bhuwaneshwar.",
    "Dr. Sherin Zafar, Associate Prof., Dept. of Computer Science & Engineering, Jamia Hamdard, New Delhi.",
    "Dr. Vivek Dwivedi, University Of Pretoria, South Africa.",
    "Dr. Shamala Subramaniam, Universiti Putra, Malaysia.",
    "Dr. Ajay Vikram Singh, Middle East College, Masqat (Oman).",
    "Dr. Nisheeth Joshi, Banasthali Vidyapeeth, Newai.",
    "Dr. Iti Mathur, Banasthali Vidyapeeth, Newai.",
    "Dr. Dharmendra Saini, BVCOE, New Delhi (INDIA).",
    "Dr. Anupam Baliyan, BVICAM, New Delhi (INDIA).",
    "Prof. Manish Shrimali, Professor, CS, Rajasthan Vidyapeeth University, Udaipur.",
    "Prof. Satyadhyan Chickerur, Hyderabad.",
    "Prof. Ajith Abraham, Machine Intelligence Research, USA.",
    "Prof. Arun Kumar Somani, Iowa State University, USA.",
    "Prof. Prashant Sahai Saxena, Director-DE, JECRC University, Jaipur."
  ];