export const headerOptions = [
  {
    id: 1,
    href: "/",
    value: "Home",
    hasOptions: true,
    options: [
      { id: 1, href: "/mpteas", value: "About MP-TEAS" },
      { id: 2, href: "/aco", value: "About Conference Organizers" },
      { id: 3, href: "/venue", value: "Venue" },
      { id: 4, href: "/aim", value: "Aim & Objectives" },
    ],
  },
  {
    id: 2,
    href: "/",
    value: "Authors",
    hasOptions: true,
    options: [
      { id: 1, href: "/mpteas", value: "Call For Papers" },
      { id: 2, href: "/aco", value: "Important Dates" },
      { id: 3, href: "/venue", value: "Author Guidelines & Submission" },
      { id: 4, href: "/aim", value: "Publications & Indexing" },
      { id: 5, href: "/aim", value: "Conference Tracks" },
      { id: 5, href: "/aim", value: "Registrations" },
    ],
  },
  {
    id: 3,
    href: "/committees",
    value: "Committees",
    hasOptions: true,
    options: [
      { id: 1, href: "/", value: "Conference Organizers & Boards" },
      { id: 1, href: "/", value: "Patron/Copatron/General chair" },
      { id: 1, href: "/", value: "Advisory Chairs" },
      { id: 1, href: "/", value: "PC Chairs Convenor / Co-Chairs" },
      {
        id: 1,
        href: "/",
        value:
          "Organizing Secretary / Co-Organizing Secretary / Joint Secretary",
      },
      { id: 1, href: "/", value: "Organizing Committee" },
    ],
  },
  {
    id: 4,
    href: "/conferenceinfo",
    value: "ConferenceInfo",
    hasOptions: true,
    options: [
      { id: 1, href: "/", value: "Eminent Guests of Honors" },
      { id: 1, href: "/", value: "Keynote Speakers" },
      { id: 1, href: "/", value: "Invited Speaker(s) / Session Chair(s)" },
    ],
  },
  {
    id: 5,
    href: "/ssp",
    value: "Special Session Proposals",
    hasOptions: true,
    options: [
      { id: 1, href: "/", value: "Proposal Guidelines" },
      { id: 1, href: "/", value: "Submission for Special Sessions" },
      { id: 1, href: "/", value: "Proceedings" },
      { id: 1, href: "/", value: "Tracks" },
      { id: 1, href: "/", value: "Paper Categories" },
    ],
  },
  {
    id: 6,
    href: "/travel",
    value: "Travel & Visa",
    hasOptions: false,
    options: [{ id: 1, href: "/", value: "" }],
  },
  {
    id: 7,
    href: "/contact",
    value: "Contact Us",
    hasOptions: false,
    options: [{ id: 1, href: "/", value: "" }],
  },
  {
    id: 8,
    href: "/schedule",
    value: "Schedule",
    hasOptions: false,
    options: [{ id: 1, href: "/", value: "" }],
  },
];
